[client]
# The URL of the minecraft server you wish to fetch mods from. This should be supplied by your server administrator
remoteServer = "https://localhost:8080/"
# The name of the file we will use to store your private key. Do NOT share the contents of this file with anyone. EVER
key = "private.key"
# The name of the file we will use to store your signed certificate from the server.
certificate = "servercert.pem"
